### ISSUE TITLE
Build error on Linux (with cross-platform UI, - the solution won't build on *nix anyway with a WPF project)

### ISSUE THREAD

**Issue by maximilien-noal** [paulirwin/JavaToCSharp#52]
```
>dotnet build
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
  All projects are up-to-date for restore.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning : Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Environment.FailFast(System.String) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.GlobalizationMode..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureData.CreateCultureWithInvariantData() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureData.get_Invariant() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureInfo..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.StringComparer..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.Loader.AssemblyDependencyResolver..ctor(System.String) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterContext+IsolatedAssemblyLoadContext..ctor(System.String, Boolean) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterContext..ctor(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1.MoveNext() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool.ExecuteAsync(System.String[], System.Threading.CancellationToken) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0.MoveNext() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool.Main(System.String[], System.Threading.CancellationToken) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at ikvmc.Program.Main(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at ikvmc.Program.<Main>(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): error MSB4181: The "IkvmCompiler" task returned false but did not log an error. [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]

Build FAILED.

/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning : Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Environment.FailFast(System.String) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.GlobalizationMode..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureData.CreateCultureWithInvariantData() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureData.get_Invariant() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Globalization.CultureInfo..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.StringComparer..cctor() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.Loader.AssemblyDependencyResolver..ctor(System.String) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterContext+IsolatedAssemblyLoadContext..ctor(System.String, Boolean) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterContext..ctor(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1.MoveNext() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool.ExecuteAsync(System.String[], System.Threading.CancellationToken) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0.MoveNext() [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at IKVM.Tools.Importer.IkvmImporterTool.Main(System.String[], System.Threading.CancellationToken) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at ikvmc.Program.Main(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): warning :    at ikvmc.Program.<Main>(System.String[]) [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
/home/max/.nuget/packages/ikvm/8.6.2/buildTransitive/IKVM.Tasks.targets(33,9): error MSB4181: The "IkvmCompiler" task returned false but did not log an error. [/home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj]
    27 Warning(s)
    1 Error(s)

Time Elapsed 00:00:10.45
F:\feature/xplatgui\dirty\home\max\source\repos\JavaToCSharp>
```

**Comment by maximilien-noal** [comment]
Latest master:

```
>dotnet build
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  Restored /home/max/source/repos/JavaToCSharp/JavaToCSharp/JavaToCSharp.csproj (in 1.75 sec).
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
  Restored /home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj (in 32.4 sec).
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(12,7): error CS0246: The type or namespace name 'JavaToCSharp' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(295,38): error CS0246: The type or namespace name 'JavaConversionOptions' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(364,55): error CS0246: The type or namespace name 'ConversionStateChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(389,67): error CS0246: The type or namespace name 'ConversionWarningEventArgs' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]

Build FAILED.

/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved. [/home/max/source/repos/JavaToCSharp/JavaToCSharp.sln]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.CSharp.Scripting 3.8.0 requires Microsoft.CodeAnalysis.CSharp (= 3.8.0) but version Microsoft.CodeAnalysis.CSharp 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj : warning NU1608: Detected package version outside of dependency constraint: Microsoft.CodeAnalysis.Scripting.Common 3.8.0 requires Microsoft.CodeAnalysis.Common (= 3.8.0) but version Microsoft.CodeAnalysis.Common 4.6.0 was resolved.
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(12,7): error CS0246: The type or namespace name 'JavaToCSharp' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(295,38): error CS0246: The type or namespace name 'JavaConversionOptions' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(364,55): error CS0246: The type or namespace name 'ConversionStateChangedEventArgs' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/ViewModels/MainWindowViewModel.cs(389,67): error CS0246: The type or namespace name 'ConversionWarningEventArgs' could not be found (are you missing a using directive or an assembly reference?) [/home/max/source/repos/JavaToCSharp/JavaToCSharpGui/JavaToCSharpGui.csproj]
    6 Warning(s)
    4 Error(s)

Time Elapsed 00:00:43.13
```

**Comment by paulirwin** [comment]
@maximilien-noal This is now fixed in master. Note that this most recent error was because of changes in your PR #54 😄 The non-GUI projects were selected to not build as part of the solution. I added those build configurations back for Debug builds. I've also added a Linux build to the GitHub Actions pipeline to help ensure this in the future as well. Thanks!

**Comment by maximilien-noal** [comment]
Oh yeah I had forgotten about that. Nice catch !

**Comment by paulirwin** [comment]
Fixed unit tests due to line endings on Linux, builds successfully in the Actions pipeline now. Thanks for bringing this to my attention!

**Comment by maximilien-noal** [comment]
I still have this error when trying to build with JetBrains Rider with dotnet 6.0, on Ubuntu 23.10:

```
Build with surface heuristics started at 14:10:55
Use build tool: /usr/lib/dotnet/sdk/7.0.110/MSBuild.dll
CONSOLE: MSBuild version 17.4.8+6918b863a for .NET
CONSOLE: Build started 8/19/2023 2:10:55PM.
CONSOLE: Project "/tmp/JetBrainsPerUserTemp-1000-1/Tizyliq.proj" on node 1 (default targets).
CONSOLE: ControllerTarget:
CONSOLE:   Run controller from /snap/rider/400/lib/ReSharperHost/JetBrains.Platform.MsBuildTask.v17.dll
0>------- Started building project: JavaToCSharp
0>IKVM.Tasks.targets(33,9): Warning  : Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Environment.FailFast(System.String)
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Globalization.GlobalizationMode..cctor()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Globalization.CultureData.CreateCultureWithInvariantData()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Globalization.CultureData.get_Invariant()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Globalization.CultureInfo..cctor()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.StringComparer..cctor()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Runtime.Loader.AssemblyDependencyResolver..ctor(System.String)
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterContext+IsolatedAssemblyLoadContext..ctor(System.String, Boolean)
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterContext..ctor(System.String[])
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1.MoveNext()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef)
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<ExecuteAsync>d__1, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<ExecuteAsync>d__1 ByRef)
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterTool.ExecuteAsync(System.String[], System.Threading.CancellationToken)
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0.MoveNext()
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef)
0>IKVM.Tasks.targets(33,9): Warning  :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[IKVM.Tools.Importer.IkvmImporterTool+<Main>d__0, IKVM.Tools.Importer, Version=8.6.2.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58]](<Main>d__0 ByRef)
0>IKVM.Tasks.targets(33,9): Warning  :    at IKVM.Tools.Importer.IkvmImporterTool.Main(System.String[], System.Threading.CancellationToken)
0>IKVM.Tasks.targets(33,9): Warning  :    at ikvmc.Program.Main(System.String[])
0>IKVM.Tasks.targets(33,9): Warning  :    at ikvmc.Program.<Main>(System.String[])
0>IKVM.Tasks.targets(33,9): Error MSB4181 : The "IkvmCompiler" task returned false but did not log an error.
0>------- Finished building project: JavaToCSharp. Succeeded: False. Errors: 1. Warnings: 21
Build completed in 00:00:03.029
```

**Comment by paulirwin** [comment]
Can you confirm if you have an ICU package installed on your system? You can see a similar issue here on the IKVM GitHub, there might also be some variables you need to set... https://github.com/ikvmnet/ikvm/issues/255#issuecomment-1373577663

There are some additional tips here such as disabling globalization support as a last resort: https://stackoverflow.com/questions/59119904/process-terminated-couldnt-find-a-valid-icu-package-installed-on-the-system-in

We are successfully building and running unit tests on ubuntu-latest in GitHub actions now (without having to do any special installs to that container besides .NET 7 SDK), so that indicates it might be something on how your local machine is configured. Let me know if any of this helps, thanks!

**Comment by maximilien-noal** [comment]
I installed both .NET 6.0 and .NET 7.0 SDKs via the package manager, and it installs all the deps for me, including libicu72.

**Comment by paulirwin** [comment]
@maximilien-noal I just tried on an x64 Ubuntu 22.04 box and it builds and runs the CLI. (I was SSH'ed in, so have not yet tried the GUI on Linux.) Did you install the dotnet SDK via [packages.microsoft.com instructions here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)? If not you might want to uninstall the SDK and reinstall using that apt source.

**Comment by maximilien-noal** [comment]
I used apt to install it from the Ubuntu 23.10 repositories.

In other words:

```
sudo apt install dotnet-sdk-6.0
```

Which corresponds to:



Package manager(Ubuntu feed) | Usually the latest version is available.Patches are available right way.Dependencies are included.Easy removal. | .NET versions available vary by Ubuntu version.Preview releases aren't available.Only supports x64 Ubuntu. (Except for Ubuntu 23.04+, which also supports Arm64)
-- | -- | --
